### ISSUE TITLE
Make it more clear that the open_sesame command opens doors directly adjacent to the walker.

### ISSUE THREAD

**Issue by spyrosoft** [gotyaoi/imhotep#14]

**Comment by gotyaoi** [comment]
is this already enough, or did you have more in mind? https://github.com/gotyaoi/imhotep/blob/master/maze/solution/exercise5.py#L16

**Comment by spyrosoft** [comment]
That's perfect. This was a struggling point of one of the participants after you had left.

**Comment by gotyaoi** [comment]
Well, the thing is, that's the wording that was there during the class, I haven't changed it. Do you think it wasn't clear enough, or that we need to emphasize reading the commnets there or something?

**Comment by spyrosoft** [comment]
Oh, I made the issue right after he told me. I didn't fact check him. It seems pretty obvious to me. If people don't read the instructions completely, it's going to be hard to make the correct solution. I think it's fine as is.
